from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Date, Float, Integer, JSON, String

Base = declarative_base()


class Example(Base):
    __tablename__ = 'example'
    id = Column(Integer, primary_key=True)
    column_a = Column(String)
    column_b = Column(String)


class StockPrice(Base):
    __tablename__ = 'StockPrices'
    # Combination of these two fields is the primary key, not each one as a primary key
    symbol = Column(String, primary_key=True)
    date = Column(Date, primary_key=True)
    price = Column(Float)  # The default currency is USD

    def __eq__(self, other):
        if self.symbol == other.symbol and self.date == other.date:
            return True
        return False


class ExchangeRate(Base):
    """Base currency is USD"""
    __tablename__ = 'ExchangeRates'
    date = Column(Date, primary_key=True)
    rates = Column(JSON)

    def __eq__(self, other):
        if self.date == other.date:
            return True
        return False

    # Down below is another implementation, it is good when we want to make computations over exchange rates
    # AED = Column(Float)
    # AFN = Column(Float)
    # ALL = Column(Float)
    # AMD = Column(Float)
    # ANG = Column(Float)
    # AOA = Column(Float)
    # ARS = Column(Float)
    # AUD = Column(Float)
    # AWG = Column(Float)
    # AZN = Column(Float)
    # BAM = Column(Float)
    # BBD = Column(Float)
    # BDT = Column(Float)
    # BGN = Column(Float)
    # BHD = Column(Float)
    # BIF = Column(Float)
    # BMD = Column(Float)
    # BND = Column(Float)
    # BOB = Column(Float)
    # BRL = Column(Float)
    # BSD = Column(Float)
    # BTC = Column(Float)
    # BTN = Column(Float)
    # BWP = Column(Float)
    # BYN = Column(Float)
    # BYR = Column(Float)
    # BZD = Column(Float)
    # CAD = Column(Float)
    # CDF = Column(Float)
    # CHF = Column(Float)
    # CLF = Column(Float)
    # CLP = Column(Float)
    # CNY = Column(Float)
    # COP = Column(Float)
    # CRC = Column(Float)
    # CUC = Column(Float)
    # CUP = Column(Float)
    # CVE = Column(Float)
    # CZK = Column(Float)
    # DJF = Column(Float)
    # DKK = Column(Float)
    # DOP = Column(Float)
    # DZD = Column(Float)
    # EGP = Column(Float)
    # ERN = Column(Float)
    # ETB = Column(Float)
    # EUR = Column(Float)
    # FJD = Column(Float)
    # FKP = Column(Float)
    # GBP = Column(Float)
    # GEL = Column(Float)
    # GGP = Column(Float)
    # GHS = Column(Float)
    # GIP = Column(Float)
    # GMD = Column(Float)
    # GNF = Column(Float)
    # GTQ = Column(Float)
    # GYD = Column(Float)
    # HKD = Column(Float)
    # HNL = Column(Float)
    # HRK = Column(Float)
    # HTG = Column(Float)
    # HUF = Column(Float)
    # IDR = Column(Float)
    # ILS = Column(Float)
    # IMP = Column(Float)
    # INR = Column(Float)
    # IQD = Column(Float)
    # IRR = Column(Float)
    # ISK = Column(Float)
    # JEP = Column(Float)
    # JMD = Column(Float)
    # JOD = Column(Float)
    # JPY = Column(Float)
    # KES = Column(Float)
    # KGS = Column(Float)
    # KHR = Column(Float)
    # KMF = Column(Float)
    # KPW = Column(Float)
    # KRW = Column(Float)
    # KWD = Column(Float)
    # KYD = Column(Float)
    # KZT = Column(Float)
    # LAK = Column(Float)
    # LBP = Column(Float)
    # LKR = Column(Float)
    # LRD = Column(Float)
    # LSL = Column(Float)
    # LTL = Column(Float)
    # LVL = Column(Float)
    # LYD = Column(Float)
    # MAD = Column(Float)
    # MDL = Column(Float)
    # MGA = Column(Float)
    # MKD = Column(Float)
    # MMK = Column(Float)
    # MNT = Column(Float)
    # MOP = Column(Float)
    # MRO = Column(Float)
    # MUR = Column(Float)
    # MVR = Column(Float)
    # MWK = Column(Float)
    # MXN = Column(Float)
    # MYR = Column(Float)
    # MZN = Column(Float)
    # NAD = Column(Float)
    # NGN = Column(Float)
    # NIO = Column(Float)
    # NOK = Column(Float)
    # NPR = Column(Float)
    # NZD = Column(Float)
    # OMR = Column(Float)
    # PAB = Column(Float)
    # PEN = Column(Float)
    # PGK = Column(Float)
    # PHP = Column(Float)
    # PKR = Column(Float)
    # PLN = Column(Float)
    # PYG = Column(Float)
    # QAR = Column(Float)
    # RON = Column(Float)
    # RSD = Column(Float)
    # RUB = Column(Float)
    # RWF = Column(Float)
    # SAR = Column(Float)
    # SBD = Column(Float)
    # SCR = Column(Float)
    # SDG = Column(Float)
    # SEK = Column(Float)
    # SGD = Column(Float)
    # SHP = Column(Float)
    # SLL = Column(Float)
    # SOS = Column(Float)
    # SRD = Column(Float)
    # STD = Column(Float)
    # SVC = Column(Float)
    # SYP = Column(Float)
    # SZL = Column(Float)
    # THB = Column(Float)
    # TJS = Column(Float)
    # TMT = Column(Float)
    # TND = Column(Float)
    # TOP = Column(Float)
    # TRY = Column(Float)
    # TTD = Column(Float)
    # TWD = Column(Float)
    # TZS = Column(Float)
    # UAH = Column(Float)
    # UGX = Column(Float)
    # USD = Column(Float)
    # UYU = Column(Float)
    # UZS = Column(Float)
    # VND = Column(Float)
    # VUV = Column(Float)
    # WST = Column(Float)
    # XAF = Column(Float)
    # XAG = Column(Float)
    # XAU = Column(Float)
    # XCD = Column(Float)
    # XDR = Column(Float)
    # XOF = Column(Float)
    # XPF = Column(Float)
    # YER = Column(Float)
    # ZAR = Column(Float)
    # ZMK = Column(Float)
    # ZMW = Column(Float)
    # ZWL = Column(Float)
